### ISSUE TITLE
Error on 'corber init' after installation on ember project

### ISSUE THREAD

**Issue by alexmasita** [isleofcode/corber#366]
Hi There.

Just tried using this library on a new ember project as described on the installation/quickstart page but have the following error after installation on running: `corber init`.
`EmberCordovaError: No ember-cordova/config/framework.js found`
However, on checking the folder structure, I see the following folders are added including the framework.js file.

```
ember-cordova
      config
           framework.js (it is actually there.)
      cordova
```

Re-running `corber init` the second time even after verifying framework.js is there still throws the same error above.

Or is it something I am doing wrong?

Also, on your installation/quickstart page, you state to use the following command after installation:

From a supported JS projected, run `et init`.

The above generates the following error: `-bash: et: command not found`

Reverting to the ember-cordova repository allows me to launch the ember app on the android simulator successfully, however, It appears some object resolutions are not working correctly when running: 

`ember cdv:build --platform=android --environment=production`

For instance if you set up a new Ember App with ember-cordova (using my versions below), the 'Welcome to Ember' component does not render on the android studio emulator.  But adding a header tag just above the component, as seen below, just displays and only displays the header.

```
<h1>Just Checking</h1>    {{!-- this displays on emulator --}}
{{welcome-page}}         {{!-- this DOES NOT display on emulator --}}
{{outlet}}
```
However, when I run the build in debug: `ember cdv:build --platform=android`, the 'welcome page above displays correctly.  It appears perhaps that minification of the js/css files when building for production breaks the code.

Am using the following libraries:

Ember Inspector | 2.1.0
Ember | 2.14.1
Ember Data | 2.14.10
jQuery | 3.2.1
WayFinder | 0.0.0+31acbcc0

Many thanks.

**Comment by alexblom** [comment]
You are definitely not doing anything wrong re: the framework error.  Can you possibly paste me the contents of your config/framework.js?

**Comment by alexmasita** [comment]
Sure thing.  Here below are the contents:

const EmberFramework = require('corber/lib/frameworks/ember/framework');

```
module.exports = EmberFramework.extend({
});
```
That is all.

**Comment by alexblom** [comment]
Thanks for the report. This has been resolved in #367

**Comment by kbullaughey** [comment]
I'm still seeing this with the current head (6d340e9b4) as reported by yarn.

All I did was:

    ember new my-app --yarn
    cd my-app
    corber init

I get this error:

    EmberCordovaError: No ember-cordova/config/framework.js found

But I do have that file with the same content reported above.

**Comment by alexblom** [comment]
@kbullaughey Thanks. If I can ask, did you install with yarn or npm?

Can you possibly try `npm install -g corber` and let me know if the results are different?

**Comment by alexblom** [comment]
Fix inbound in #372, just awaiting travis to pass

**Comment by alexblom** [comment]
Resolved in 1.1.0-beta.5. This behaviour likely only affected yarn installs.

**Comment by alexmasita** [comment]
Hi Alex.  

A light bulb went off when you mentioned a possible yarn conflict.  I went back and uninstalled corber locally and globally via npm and also via yarn.  Now the issue is resolved.  It appears even though I was installing the latest corber release globally via npm, the earlier yarn version was somehow interfering with the execution.

Many thanks again.

**Comment by kbullaughey** [comment]
I had originally, and unknowingly installed with npm. Meant to install with yarn. I've now installed beta.5 globally with yarn and it works.

**Comment by lele-melis** [comment]
I am getting what appears to be a related issue, with the same symptoms, of getting

`EmberCordovaError: No ember-cordova/config/framework.js found`

on init.

It is non-deterministic, out of 5 tries I can manage to get one or two "init" to finish correctly. Could not manage to find the discriminant between each run with the successful ones.
I am on node lts 6.13, using npm.
