### ISSUE TITLE
Problems after corber.init in emberjs project

### ISSUE THREAD

**Issue by mssod** [isleofcode/corber#387]
Hi there,

moving from ember-cordova following the quickstart instructions. In a new created emberjs app:

ember-cli: 2.15.0
node: 6.2.0
os: darwin x64

cordova: 7.1.0

After npm install -g corber and corber.init the following stack trace

process is not captured
Error: process is not captured
    at Object.addHandler (/Users/dossm/.nodenv/versions/6.2.0/lib/node_modules/corber/node_modules/ember-cli/lib/utilities/will-interrupt-process.js:81:13)
    at Promise.resolve.then (/Users/dossm/.nodenv/versions/6.2.0/lib/node_modules/corber/node_modules/ember-cli/lib/cli/cli.js:157:28)
    at tryCatch (/Users/dossm/.nodenv/versions/6.2.0/lib/node_modules/corber/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/dossm/.nodenv/versions/6.2.0/lib/node_modules/corber/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/dossm/.nodenv/versions/6.2.0/lib/node_modules/corber/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/dossm/.nodenv/versions/6.2.0/lib/node_modules/corber/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)

Many thanks

**Comment by benjaminbalazs** [comment]
Same here with node 8.6, ember-cli 2.16.1.

**Comment by wytlytningNZ** [comment]
Also receiving the same error:
node 6.11.0, ember-cli ~2.16.2 & ~2.14.1

**Comment by alexblom** [comment]
Thanks for the report. This is fixed in 1.1.1, with a better fix coming when we merge #386.

**Comment by alexblom** [comment]
Further fixes in 1.1.2 - bin consumes our version of ember-cli to avoid issues like this in the future.

**Comment by xcambar** [comment]
Unfortunately, the problem remains on a fresh install with

node 8.7.0
npm 5.4.2
ember-cli 2.16.2
corber 1.1.2
