### ISSUE TITLE
corber start with android device doesn't overwrite existing app

### ISSUE THREAD

**Issue by DuBistKomisch** [isleofcode/corber#589]
Seems like expected behaviour.

https://github.com/isleofcode/corber/blob/d9175bf7b2a5b2990bd4dec07d73c5222d572975/lib/targets/android/tasks/install-app-device.js#L9

Needs the `-r` flag here to do so, like the emulator version:

https://github.com/isleofcode/corber/blob/d9175bf7b2a5b2990bd4dec07d73c5222d572975/lib/targets/android/tasks/install-app-emulator.js#L9

**Comment by alexblom** [comment]
Thanks - we were not really thinking through an app already being installed. I'll work on a patch this week.

**Comment by alexblom** [comment]
We're targeting a release for next week - however this is fixed on master if you are blocked right now.

**Comment by DuBistKomisch** [comment]
No rush, can just uninstall manually for now, thanks!

**Comment by DuBistKomisch** [comment]
Hmm, `-r` still doesn't work to overwrite the app store version of the app, you get `INSTALL_FAILED_UPDATE_INCOMPATIBLE` complaining about the signatures not matching. You have to `adb uninstall` it first, but this is probably beyond what corber should be doing.
