### ISSUE TITLE
can't build or start with `--platform=android`

### ISSUE THREAD

**Issue by jamesdixon** [isleofcode/corber#603]
Hi @alexblom ,

I'm having an issue building/starting Android using Corber.

I ran the following commands which resulted in the below error:

```
odin:hg-mobile jamesdixon$ corber platform add android
adding platform 'android'...
Initializing cordova with default WebView
added platform 'android'
odin:hg-mobile jamesdixon$ corber build --platform=android
corber: Building app
'android' is not an installed platform
Cannot read property 'signingIdentityValidation' of undefined


Stack Trace and Error Report: /var/folders/n9/6m8fhkhn4bjfnvsdj8pyzks80000gn/T/error.dump.28bf550b9c31b9406ac99d8988efcebd.log
```

I can see that the `platforms/` directory does contain an `android` project after adding the platform, but attempts to use `corber build` or `corber start` fail with the error above.

When running `corber start --platform=android`, I get the following:

```
odin:hg-mobile jamesdixon$ corber start --platform=android
Corber Starting
You are passing platform=android which is not installed.
Try running corber platform add android
You are passing platform=android which is not installed.
Try running corber platform add android


Stack Trace and Error Report: /var/folders/n9/6m8fhkhn4bjfnvsdj8pyzks80000gn/T/error.dump.cf1f746303aa3ba8ef454f94a5bb0296.log```

I saw mention of a too-new JDK in #544, but running `java -version` results in:

```
odin:hg-mobile jamesdixon$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

Here's a link to the logs referenced in those error messages: https://gist.github.com/jamesdixon/205fb699ecfb99f3ad97625394afe7bd

Appreciate any insights in advance!

**Comment by jamesdixon** [comment]
turns out removing corber and re-initing fixed this 👍

**Comment by jamesdixon** [comment]
Actually, this keeps happening. I had to run `corber platform remove android` a couple of times and then add it again to get plugins to install (tried `corber prepare`, but it doesn't install plugins to the project if they've already been installed in the `plugins/` directory). Not sure exactly why, but I'll randomly get these error again and then have to remove and re-install corber. Any thoughts?

**Comment by alexblom** [comment]
I'm going to leave this open for now - but I think some of the platform patches I just merged have resolved this. Will be doing a full QA pre release tomorrow.

**Comment by alexblom** [comment]
Looks to be resolved in 1.3.10 - please let me know if your experience is otherwise!

**Comment by llunn** [comment]
@alexblom This error still occurs. In my case, removing a platform appears to remove all platforms in the `package.json`'s `platforms` attribute, which results in the same error occurring in addition to a no platforms installed error.

The relevant stack is:
```console
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'signingIdentityValidation' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'signingIdentityValidation' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'signingIdentityValidation' of undefined
    at _super.then.then.then.then.then.then.then.then.then.then.then.catch.finally (/usr/local/lib/node_modules/corber/lib/commands/build.js:121:40)
    at /usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:1117:38
    at tryCatcher (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:498:33)
    at publish (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:484:9)
    at publishRejection (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:419:5)
    at flush (/usr/local/lib/node_modules/corber/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
```

The `platforms` attribute is then not updated properly on a `corber platform add`.

It appears that the entire issue is really a cordova issue that is produced by adding a namespaced plugin (e.g. `@name/some-plugin`. Cordova fails to find the `plugin.xml` file (likely it is looking in the root directory (i.e. `@name/plugin.xml` as opposed to `@name/some-plugin/plugin.xml`. It is then manifested in corber because the exception thrown by cordova isn't being handled, and incorrect console output is shown by corber suggesting that the platform has been added correctly.

To work around this error (for conditions related to the platform):
1. `cd corber/cordova`
2. `cordova platform remove PLATFORM_NAME`
3. `cordova platform add PLATFORM_NAME`
4. `cordova plugin add PROBLEM_PLUGIN`
5. Repeat step 4 for plugins that have not been installed due to cordova throwing an exception
6. Manually add the appropriate platform to package.json;
