### ISSUE TITLE
corber not noticing installed platform

### ISSUE THREAD

**Issue by jl-cs** [isleofcode/corber#628]
I'm on Windows 10 x64 and have a project where I've successfully added the android platform via cordova. But when trying to build with "corber build --platform=android" I get the following error message: "EmberCordovaError: Validation error(s)
* cordova platform android is missing or not installed:
You probably need to run ember cdv:platform add android. cordova error: Not found in fetch.json."

Why is that and how does corber even decided which platform is installed?
Thanks for any insights.

**Comment by alexblom** [comment]
This should be fixed as of 1.4.0 - further comments in #630

**Comment by jl-cs** [comment]
Thanks for updating, but the problem is still present for me.

**Comment by jl-cs** [comment]
I found the problem that caused corber to not recognize the already installed android platform. For whatever reason the platforms.json in "ember/corber/cordova/platforms" was empty (actually it held "{}", but that made it look empty for corber). So I just added the installed android platform version so that it now looks like this:
`{
  "android": "8.1.0"
}
`
and now corber is recognizing the installed platform again. Maybe that'll help someone someday.
